const fs = require('fs');
const path = require('path');
fs.writeFileSync('notes.txt', 'Name: Gul E Haram\nRoll no: 2502111\nCourse: Web Technologies');
fs.appendFileSync('notes.txt', '\nMore text added.');
console.log('File created!');
const content = fs.readFileSync('notes.txt', 'utf8');
console.log('File says: ' + content);
const exists = fs.existsSync('notes.txt');
console.log('File exists? ' + exists);
console.log('Current folder: ' + __dirname);
console.log('Full path: ' + path.join(__dirname, 'notes.txt'));
